### ISSUE TITLE
Upgrade Elasticsearch to 5.0.0

### ISSUE THREAD

**Issue by aeneaswiener** [pires/docker-elasticsearch-kubernetes#19]
Are you planning an upgrade to [v5.0.0](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/release-notes-5.0.0.html)?

**Comment by pires** [comment]
@aeneaswiener unfortunately, it's not trivial. See https://github.com/pires/kubernetes-elasticsearch-cluster/issues/60#issuecomment-257300398.

**Comment by pires** [comment]
Done.
