### ISSUE TITLE
Got KubernetesClientException when running this docker image

### ISSUE THREAD

**Issue by zhuc** [pires/docker-elasticsearch-kubernetes#24]
When I tried to run this docker image on my linux server, it throw out this warning:
> [WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [fd_rT8G] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
I'm using the latest 5.1.1 docker image.

The command to start the docker is:

`docker run -d --privileged   -p 9201:9200 -p 9301:9300 quay.io/pires/docker-elasticsearch-kubernetes:5.1.1`

Can you help on this? Thank you!

**Comment by zhuc** [comment]
Here's the full log.
### > [2016-12-22T09:40:58,819][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/elasticsearch/config/logging.yml], logging is configured via [/elasticsearch/config/log4j2.properties]
> [2016-12-22T09:40:59,106][INFO ][o.e.n.Node               ] [] initializing ...
> [2016-12-22T09:40:59,182][INFO ][o.e.e.NodeEnvironment    ] [fd_rT8G] using [1] data paths, mounts [[/data (/dev/xvda2)]], net usable_space [75.4gb], net total_space [98gb], spins? [no], types [ext3]
> [2016-12-22T09:40:59,183][INFO ][o.e.e.NodeEnvironment    ] [fd_rT8G] heap size [494.9mb], compressed ordinary object pointers [true]
> [2016-12-22T09:40:59,184][INFO ][o.e.n.Node               ] node name [fd_rT8G] derived from node ID [fd_rT8GPSbmLEXqDtuz26w]; set [node.name] to override
> [2016-12-22T09:40:59,187][INFO ][o.e.n.Node               ] version[5.1.1], pid[18], build[5395e21/2016-12-06T12:36:15.409Z], OS[Linux/3.10.0-327.22.2.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_111-internal/25.111-b14]
> [2016-12-22T09:41:00,286][INFO ][o.e.p.PluginsService     ] [fd_rT8G] loaded module [aggs-matrix-stats]
> [2016-12-22T09:41:00,287][INFO ][o.e.p.PluginsService     ] [fd_rT8G] loaded module [ingest-common]
> [2016-12-22T09:41:00,287][INFO ][o.e.p.PluginsService     ] [fd_rT8G] loaded module [lang-expression]
> [2016-12-22T09:41:00,287][INFO ][o.e.p.PluginsService     ] [fd_rT8G] loaded module [lang-groovy]
> [2016-12-22T09:41:00,287][INFO ][o.e.p.PluginsService     ] [fd_rT8G] loaded module [lang-mustache]
> [2016-12-22T09:41:00,287][INFO ][o.e.p.PluginsService     ] [fd_rT8G] loaded module [lang-painless]
> [2016-12-22T09:41:00,287][INFO ][o.e.p.PluginsService     ] [fd_rT8G] loaded module [percolator]
> [2016-12-22T09:41:00,288][INFO ][o.e.p.PluginsService     ] [fd_rT8G] loaded module [reindex]
> [2016-12-22T09:41:00,288][INFO ][o.e.p.PluginsService     ] [fd_rT8G] loaded module [transport-netty3]
> [2016-12-22T09:41:00,288][INFO ][o.e.p.PluginsService     ] [fd_rT8G] loaded module [transport-netty4]
> [2016-12-22T09:41:00,288][INFO ][o.e.p.PluginsService     ] [fd_rT8G] loaded plugin [discovery-kubernetes]
> [2016-12-22T09:41:02,437][INFO ][o.e.n.Node               ] initialized
> [2016-12-22T09:41:02,437][INFO ][o.e.n.Node               ] [fd_rT8G] starting ...
> [2016-12-22T09:41:02,603][INFO ][o.e.t.TransportService   ] [fd_rT8G] publish_address {172.17.90.4:9300}, bound_addresses {172.17.90.4:9300}
> [2016-12-22T09:41:02,609][INFO ][o.e.b.BootstrapCheck     ] [fd_rT8G] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> [2016-12-22T09:41:03,038][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [fd_rT8G] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
> [2016-12-22T09:41:04,555][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [fd_rT8G] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
> [2016-12-22T09:41:06,060][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [fd_rT8G] Exception caught during discovery: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
> [2016-12-22T09:41:06,086][INFO ][o.e.c.s.ClusterService   ] [fd_rT8G] new_master {fd_rT8G}{fd_rT8GPSbmLEXqDtuz26w}{Yvr72zwvSf20lTydJuJhUQ}{172.17.90.4}{172.17.90.4:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
> [2016-12-22T09:41:06,103][INFO ][o.e.h.HttpServer         ] [fd_rT8G] publish_address {172.17.90.4:9200}, bound_addresses {172.17.90.4:9200}
> [2016-12-22T09:41:06,103][INFO ][o.e.n.Node               ] [fd_rT8G] started
> [2016-12-22T09:41:06,114][INFO ][o.e.g.GatewayService     ] [fd_rT8G] recovered [0] indices into cluster_state

**Comment by pires** [comment]
This image is to be used from within Kubernetes and not directly with Docker or any other compatible container runtime. For that, use [this other image](https://github.com/pires/docker-elasticsearch).
