### ISSUE TITLE
Elasticsearch logs is written to file as well as stdout

### ISSUE THREAD

**Issue by gtcno** [pires/docker-elasticsearch-kubernetes#25]
Hi

We are having issues with elasticsearch logs using a lot of  disks. Would it be an idea to just make ES log to stdout for this image? 

An alternative is adding a cron job to the image that cleans up the daily rotated logs. 
We would like hear your thought and would also gladly help with a PR.

**Comment by pires** [comment]
Rotating logs from within containers didn't use to work for host Docker logs, so I'm not sure what you suggest will fix it.

**Comment by gtcno** [comment]
To be more precise.

We encountered a problem when runnning this image in a kubernetes cluster with a persistent disk.
The elasticsearch logs would fill the disk, as we had no good method of removing them(docker exec into the container and removing the logs manually is not a good method:) )

So we had to to fork the image and send all elasticsearch logs to standard out, and using 
--log-opt max-size --log-opt max-file do rotated the docker logs on the host.

**Comment by pires** [comment]
@gtcno this in a Kubernetes cluster? I'm open to review PRs 👍

**Comment by pires** [comment]
One thing is to not fill the container log files, which I get and could do with a CronJob that rotates said files. A different thing is to rotate on the node itself, but could also be solved with a different CronJob. I wonder what @puja108 and the GiantSwarm team has in place ;)

**Comment by pires** [comment]
Moving this over to https://github.com/pires/kubernetes-elasticsearch-cluster/issues/70.
