### ISSUE TITLE
License file does not have correct license information in it

### ISSUE THREAD

**Issue by btipling** [pires/docker-elasticsearch-kubernetes#27]
It just has the unfilled template variables in it.

**Comment by pires** [comment]
Supposedly, the template should be used in every source file, e.g. Dockerfile, code, README.md.. and that's just too much work for nothing. Feel free to do whatever you wish to this repo. I hereby confirm everything in this repo is under APL 2.0.

**Comment by btipling** [comment]
I just meant that you should fill in the author name instead of leaving it  `   Copyright {yyyy} {name of copyright owner}`

**Comment by btipling** [comment]
@pires I just meant that you might want to fill in the author name instead of leaving it as literally `   Copyright {yyyy} {name of copyright owner}` 

https://github.com/pires/docker-elasticsearch-kubernetes/blob/master/LICENSE#L189
