### ISSUE TITLE
Could have xpack installed by default?

### ISSUE THREAD

**Issue by zfy0701** [pires/docker-elasticsearch-kubernetes#37]

**Comment by pires** [comment]
Possibly or just provide a new image that contains it. I'll look into it soon.

**Comment by artushin** [comment]
Added https://github.com/pires/docker-elasticsearch/pull/30

Tested with https://hub.docker.com/r/artushin/docker-elasticsearch-kubernetes/ and seems to work.

**Comment by pires** [comment]
Merged! Will release new versions tomorrow with a fix for an unrelated bug.
