### ISSUE TITLE
Alpine doesn't work with kubernetes

### ISSUE THREAD

**Issue by onorua** [pires/docker-elasticsearch-kubernetes#4]
You have moved to Alpine linux quite some time ago (https://github.com/pires/docker-jre/commit/00104da058777615fc015cae7b6079102afa6ffa), since that moment kubernetes elasticsearch doesn't work. The reason is simple - alpine doesn't support `search` parameter in resolve.conf. 
The plugin for kubernetes node discovery has `kubernetes.default.svc` as desitnation name, but kubernetes DNS doesn't have this address completely, but domain name search instead... so as a result - this builds are useless since that commit. 
I see 2 options:
 1. change name in plugin to `kubernetes.default.svc.cluster.local`
 2. move to debian or any other base image with normal glibc.

**Comment by pires** [comment]
@onorua can you share logs that prove this is failing?
