### ISSUE TITLE
question about environment variables

### ISSUE THREAD

**Issue by zetab** [pires/docker-elasticsearch-kubernetes#40]
Is this image really using fabric8 kubernetes plugin at all? Links in readme goes to fabric8 documentation, but elasticsearch config file does not contain that stuff? And I cannot see that fabric8 plugin installed? Anyways it looks like this docker image is working, i can create elasticsearch cluster to kubernetes which really works (i can kill pods etc and still it can recover its state)

**Comment by pires** [comment]
Where are the links in the README.md that point to the fabric8 discovery plug-in?

**Comment by pires** [comment]
You're right, how have I missed that? You could have linked the lines though ;)
