### ISSUE TITLE
Stateful Example not working due to: StatefulSet in version "v1alpha1" cannot be handled as a StatefulSet: no kind "StatefulSet" is registered for version "apps/v1alpha1"

### ISSUE THREAD

**Issue by xamox** [pires/docker-elasticsearch-kubernetes#41]
I get the following error:
```Error from server (BadRequest): error when creating "es-data-stateful.yaml": StatefulSet in version "v1alpha1" cannot be handled as a StatefulSet: no kind "StatefulSet" is registered for version "apps/v1alpha1"```

I read that stateful sets were introduced in k8s version 1.5.  I'm using 1.5.2, do I need to be using 1.6? 

Here is my version info:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by xamox** [comment]
Just a follow up.  I upgraded to kubernetes v1.6.1 and still getting issues:

`
± % kubectl create -f es-data-stateful.yaml                                                                                                                                                          error: error validating "es-data-stateful.yaml": error validating data: expected type array, for field spec.volumeClaimTemplates, got map; if you choose to ignore these errors, turn validation off with --validate=false`

Running with validate false I get output:

`Error from server (BadRequest): error when creating "es-data-stateful.yaml": StatefulSet in version "v1beta1" cannot be handled as a StatefulSet: only encoded map or array can be decoded into a struct`


```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by pires** [comment]
Please, re-open the issue in https://github.com/pires/kubernetes-elasticsearch-cluster.
