### ISSUE TITLE
Shard allocation awareness 

### ISSUE THREAD

**Issue by yukiman76** [pires/docker-elasticsearch-kubernetes#42]
Would love to have the ability for the ES cluster to know which compute node is currently being used so if the compute host crashes the index would still be able to recover

its a simple change to the es configuration to add an attribute that you would then route on
https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-awareness.html

**Comment by yukiman76** [comment]
something  like https://github.com/yukiman76/docker-elasticsearch-kubernetes should be a good start

**Comment by pires** [comment]
Check the answer on the other repo. I'll close this one as it doesn't belong here ;)
