### ISSUE TITLE
NFS for PS needs rpc.statd running

### ISSUE THREAD

**Issue by y2kbowen** [pires/docker-elasticsearch-kubernetes#46]
I am attempting to create a statefulset. My PS is locally hosted from an NFS share.  My storage and claims are coming online but I get the following error:

`MountVolume.SetUp failed for volume "kubernetes.io/nfs/fa7984c6-6f1a-11e7-b489-021fcfb21298-storage-es-data-0" (spec.Name: "storage-es-data-0") pod "fa7984c6-6f1a-11e7-b489-021fcfb21298" (UID: "fa7984c6-6f1a-11e7-b489-021fcfb21298") with: mount failed: exit status 32 Mounting command: mount Mounting arguments: 10.7.135.250:/vol/multiint/dev01/esearch/es001 /var/lib/kubelet/pods/fa7984c6-6f1a-11e7-b489-021fcfb21298/volumes/kubernetes.io~nfs/storage-es-data-0 nfs [] Output: mount.nfs: rpc.statd is not running but is required for remote locking. mount.nfs: Either use '-o nolock' to keep locks local, or start statd. mount.nfs: an incorrect mount option was specified 
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"es-data-1". list of unattached/unmounted volumes=[storage]
`

Maybe we need to add an NFS  package?

**Comment by pires** [comment]
This is a Kubernetes thing, not this image.
