### ISSUE TITLE
Image does not run

### ISSUE THREAD

**Issue by gschaden** [pires/docker-elasticsearch-kubernetes#54]
Using docker and in kubernetes the container keeps crashing
The only output is 
`Not setting JVM max heap size, already set
`
By setting the args to /run.sh in kubernetes, the container started as expected

**Comment by pires** [comment]
What instructions are you following? https://github.com/pires/kubernetes-elasticsearch-cluster?

**Comment by scostello-paanalytics** [comment]
@pires I was having the same issue and yes I was following the instructions at https://github.com/pires/kubernetes-elasticsearch-cluster.

**Comment by chancez** [comment]
I've seen a few reports of this too. Might be related to my PR, but I tested running it via docker locally and didn't have any issues, but I guess I wasn't checking for run.sh being run. I wonder if the issue is that both of these scripts run `exec`.

**Comment by deedubs** [comment]
I can confirm I'm seeing the same.  Running the `statefulset` example from the k-e-c repo. Going to investigate @chancez's suggestion about manually specifying `command `

**Comment by deedubs** [comment]
I've been able to start the new images with the command

```
          command:
            - /entrypoint.sh
            - su-exec 
            - elasticsearch
            - /elasticsearch/bin/elasticsearch
```

**Comment by pires** [comment]
How was I able to run this then when updating the repo with the instructions for 6.0.0? 🤔

**Comment by deedubs** [comment]
I spoke too soon

```
OVERWRITE_JVM_HEAPSIZE: true
NAMESPACE: 
NODE_NAME: 
MY_MEM_REQUEST: 1073741824
MY_MEM_LIMIT: 1073741824
```

and I'm still seeing

```
$ES_JAVA_OPTS set and JVM max heapsize already configured, but $OVERWRITE_JVM_HEAPSIZE=true, setting JVM max heap size
Setting JVM_HEAP_SIZE to 512M
[2017-12-07T16:13:53,164][INFO ][o.e.n.Node               ] [elasticsearch-master-69cc995bfb-cjtb8] initializing ...
[2017-12-07T16:13:53,460][INFO ][o.e.e.NodeEnvironment    ] [elasticsearch-master-69cc995bfb-cjtb8] using [1] data paths, mounts [[/data (/dev/xvda1)]], net usable_space [53.5gb], net total_space [62.8gb], types [ext4]
[2017-12-07T16:13:53,461][INFO ][o.e.e.NodeEnvironment    ] [elasticsearch-master-69cc995bfb-cjtb8] heap size [494.9mb], compressed ordinary object pointers [true]
```

**Comment by dwickern** [comment]
I have the same problem running it on a fresh [kubernetes-vagrant-coreos-cluster](https://github.com/pires/kubernetes-vagrant-coreos-cluster)

**Comment by chancez** [comment]
@deedubs that's what it _should_ look like. Are you saying you got it working without changing anything besides env vars?

FWIW, it seems `CMD` simply isn't running. If I just do `docker run -it  quay.io/pires/docker-elasticsearch-kubernetes:6.0.0_jre8u151 /run.sh` it does both the entrypoint and the `/run.sh`, so it doesn't seem like the scripts are interacting poorly, but rather the CMD isn't being executed for some reason.

**Comment by deedubs** [comment]
@chancez Agreed. I missed where it was dividing the resource limit to set the heap.

https://github.com/pires/docker-elasticsearch-kubernetes/blob/master/entrypoint.sh#L46 is expecting an argument but we are currently not passing on https://github.com/pires/docker-elasticsearch-kubernetes/blob/master/Dockerfile#L15

**Comment by chancez** [comment]
@deedubs The argument should come from the base image which this is built on top of at https://github.com/pires/docker-elasticsearch/blob/master/Dockerfile#L72

**Comment by pires** [comment]
Sorry for the delay but I've been really busy as of lately. I can reproduce and am working on a fix.

**Comment by pires** [comment]
Unfortunately, I had to revert @chancez PR until I figure out what's going on. Releasing 6.0.1 as we speak.

**Comment by deedubs** [comment]
@pires not sure if it'll help with your debugging but I have it running.  This is the full Statefull lSet https://gist.github.com/deedubs/c5bbbddf605794ca9a4609c23f94dc08

**Comment by pires** [comment]
@deedubs you got it working by overriding the command. I don't want that and I really can't tell why the entrypoint doesn't call the cmd or why it returns an error. Even though they're in separate Dockerfiles, I believe it should just work. I don't have the free cycles to look more deeply into it now and so the quickest solution was to simply revert the commit that broke this.

**Comment by deedubs** [comment]
Yeah exactly, not proposing it as a viable solution, just what I had to do
to move forward with 6.0(we had an external dep on 6.0).  I'll see if I can
investigate.

**Comment by chancez** [comment]
I wonder if this has to do with docker version.

**Comment by deedubs** [comment]
We're on `1.12.6` FWIW

**Comment by pires** [comment]
I test things with my kubernetes-vagrant-coreos-cluster repo and it runs CoreOS alpha which runs Docker 17.11.0, as I write this.
