### ISSUE TITLE
X-pack for elasticsearch 6.3.0 not working

### ISSUE THREAD

**Issue by lcasassa** [pires/docker-elasticsearch-kubernetes#62]
$ docker run --rm -it quay.io/pires/docker-elasticsearch-kubernetes:6.3.0 sh
/elasticsearch # elasticsearch-plugin list
mktemp: Invalid argument
/elasticsearch # 

It looks like alpine is not supported??

Is this the reason x-pack is not working in 6.3.0?

**Comment by pires** [comment]
It is working. This image is supposed to run as part of a Kubernetes cluster and not with docker run. Please see https://github.com/pires/kubernetes-elasticsearch-cluster

**Comment by pires** [comment]
The x-pack-ml had to be disabled and deleted because it doesn't support Alpine Linux (non-glibc).

**Comment by lcasassa** [comment]
Interesting, I have it already deployed working in production at Buda.com :)

But I don't see the watcher/monitor/etc links in kibana. How do I enable them?

**Comment by lcasassa** [comment]
I was using the image docker.elastic.co/kibana/kibana-oss:6.3.0 instead of docker.elastic.co/kibana/kibana:6.3.0 :P

Thanks!
