### ISSUE TITLE
Missing required field "selector" in io.k8s.api.apps.v1.StatefulSetSpec

### ISSUE THREAD

**Issue by paulavijit** [pires/docker-elasticsearch-kubernetes#63]
Executing:
kubectl apply -f es-master-stateful.yaml

Results in error:
error: error validating "es-master-stateful.yaml": error validating data: [ValidationError(StatefulSet.spec): missing required field "selector" in io.k8s.api.apps.v1.StatefulSetSpec, ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by pires** [comment]
Hello! Thanks for reporting but I think you wanted to report this on pires/kubernetes-elasticsearch-cluster repo, right?
