### ISSUE TITLE
Documentation should list OpenJRE rather than Oracle JRE

### ISSUE THREAD

**Issue by SaMnCo** [pires/docker-elasticsearch-kubernetes#8]
Hello! 
Great work adapting the production grade ES cluster and following upstream. Congrats and thanks, much appreciated. 

One (very small) comment: I was a bit confused in the documentation for this as it states "Oracle JRE" but the original docker-jre is based on OpenJDK. I think it would be more accurate to mention OpenJDK JRE 8u92 (at least atm). 

Best,

**Comment by pires** [comment]
Hi, thank you for your kind words. I used to maintain docs in the Kubernetes project but it got too cumbersome and now I only update it here. 

Regarding docs, you're right. Would you contribute a PR to fix it? Glad to merge.

**Comment by pires** [comment]
Fixed by https://github.com/pires/docker-elasticsearch-kubernetes/commit/a60e079a466d0c8fab257a963d4d19c764e17cfa.
